#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Namespace
metadata:
  name: metadata-store-secrets
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: store-ca-cert
  namespace: metadata-store-secrets
data:
  ca.crt: #@ data.values.tap.metadatastore.ca
  tls.crt: ""
  tls.key: ""
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: store-ca-cert
  namespace: metadata-store-secrets
spec:
  toNamespace: "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: store-auth-token
  namespace: metadata-store-secrets
stringData:
  auth_token: #@ data.values.tap.metadatastore.auth_token
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: store-auth-token
  namespace: metadata-store-secrets
spec:
  toNamespace: "*"


