#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: postgres-as-a-service-app
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: "postgres-as-a-service-app"
    kapp.k14s.io/change-rule.1: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.2: "upsert after upserting tap"
    kapp.k14s.io/change-rule.3: "upsert after upserting postgres-operator"
spec:
  serviceAccountName: tap-install-gitops-sa
  syncPeriod: 1m
  fetch:
  - git:
      url: #@ data.values.git.url
      ref: #@ data.values.git.ref
  template:
  - ytt:
      paths:
      - clusters/appref-2/app-contents/postgres-as-a-service
      valuesFrom:
      - secretRef:
          name: tap-install-gitops
  deploy:
  - kapp: 
      intoNs: service-instances