#@ load("@ytt:data", "data")

---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: dotnet-todos-api
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: dotnet-todos-api
    apps.tanzu.vmware.com/has-tests: "true"
  namespace: dotnet-todos
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_repository_name
      value: "trp-gitops-dotnet-todos"
    - name: language
      value: dotnet
  env:
    - name: ConnectionStrings__DefaultConnection
      valueFrom:
        secretKeyRef:
          name: api-db-credentials
          key: connection-string

  source:
    git:
      url: https://github.com/tanzu-end-to-end/dotnet-employee-todo-list-api.git
      ref:
        branch: main