#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh
  namespace: tap-install
  annotations:
    tekton.dev/git-0: #@ data.values.git.host
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: #@ data.values.git.private_key
  known_hosts: #@ data.values.git.known_hosts
  identity: #@ data.values.git.private_key
  identity.pub: #@ data.values.git.public_key
---
apiVersion: v1
kind: Secret
metadata:
  name: git-https
  namespace: tap-install
  annotations:
    tekton.dev/git-0: #@ data.values.git_pr.host
type: kubernetes.io/basic-auth 
stringData:
  username: #@ data.values.git_pr.user
  password: #@ data.values.git_pr.password
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: git-ssh
  namespace: tap-install
spec:
  toNamespaces:
  - '*'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: git-https
  namespace: tap-install
spec:
  toNamespaces:
  - '*'