---
catalog: https://github.com/tanzu-end-to-end/acme-catalog/blob/main/catalog-info.yaml
git:
  url: https://github.com/tanzu-end-to-end/tap-gitops-reference
  ref: origin/dev
paths:
 - clusters/common/config
 - clusters/appref-1/config
tap:
  cert:
    cn: '*.one.appref.end2end.link'
  registry:
    host: harbor.one.appref.end2end.link
  supplychainregistry:
    host: harbor.one.appref.end2end.link
  base:
    domain: one.appref.end2end.link
  view:
    domain: one.appref.end2end.link
  tapgui:
    domain: tap-gui.one.appref.end2end.link
  learningcenter:
    domain: learningcenter.one.appref.end2end.link
  cnr:
    domain: appref1.appref.end2end.link
  accelerator:
    domain: accelerator.one.appref.end2end.link
  metadata:
    domain: metadata-store.one.appref.end2end.link
systems:
  canary:
    gitops_repo_url: https://github.com/jeffellin/gitops-hello
  spring_petclinic:
    gitops_repo_url: https://github.com/jeffellin/gitops-spring-petclinic
