---
catalog: https://github.com/jeffellin/tap-catalog/blob/main/catalog-info.yaml
git:
  url: https://github.com/tanzu-end-to-end/tap-gitops-reference
  ref: origin/dev
paths:
 - clusters/common/config
 - clusters/appref-2/config
tap:
  cert:
    cn: '*.appref2.appref.end2end.link'
  registry:
    host: harbor.one.appref.end2end.link
  supplychainregistry:
    host: harbor.one.appref.end2end.link
  base:
    domain: appref2.appref.end2end.link
  tapgui:
    domain: tap-gui.appref2.appref.end2end.link
  learningcenter:
    domain: learningcenter.appref2.appref.end2end.link
  cnr:
    domain: appref2.appref.end2end.link
  accelerator:
    domain: accelerator.appref2.appref.end2end.link
  metadata:
    domain: metadata-store.appref1t.appref.end2end.link
systems:
  canary:
    gitops_repo_url: https://github.com/jeffellin/gitops-hello
  spring_petclinic:
    gitops_repo_url: https://github.com/jeffellin/gitops-spring-petclinic
