---
catalog: https://github.com/tanzu-end-to-end/acme-catalog/blob/main/catalog-info.yaml
git:
  url: https://github.com/tanzu-end-to-end/tap-gitops-reference
  ref: origin/dev
paths:
 - clusters/common/config
 - clusters/appref-1/config
tap:
  registry:
    host: harbor.one.appref.end2end.link
    location: jeff/tbs
  supplychainregistry:
    host: harbor.one.appref.end2end.link
    location: jeff/sc
  base:
    domain: 1-devt.appref.end2end.link
