---
catalog: ""
git:
  url: https://github.com/tanzu-end-to-end/tap-gitops-reference
  ref: origin/main
paths:
 - clusters/common/config
 - clusters/appref-2/config
tap:
  registry:
    host: harbor.one.appref.end2end.link
    location: tap/tbs
  supplychainregistry:
    host: harbor.one.appref.end2end.link
    location: tap/sc
  base:
    domain: one.appref.end2end.link
