#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ def othersecret():
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: route53-credentials
  namespace: cert-manager
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
spec:
  fromNamespace: tap-install
#@ end
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: #@ data.values.certmanager.namespace
  annotations:
    kapp.k14s.io/change-group: cert-manager
    kapp.k14s.io/change-rule: "delete after deleting tap"
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.1: certmanager-security-overlay
spec:
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      prereleases: {}
      constraints: #@ str(data.values.certmanager.version)
  serviceAccountName: tap-install-gitops-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: certmanager-security-overlay
stringData:
  othersecret.yaml: #@ yaml.encode(othersecret())
  