apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tap-bug-bash-build
  region: us-east-1
nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 4
    amiFamily: AmazonLinux2
    containerRuntime: containerd
