# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-standard
  namespace: tanzu-package-repo-global
spec:
  fetch:
    imgpkgBundle:
      image: projects.registry.vmware.com/tkg/packages/standard/repo:v1.5.4-update.1
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-core
  namespace: tanzu-package-repo-global
spec:
  fetch:
    imgpkgBundle:
      image: projects.registry.vmware.com/tkg/packages/core/repo:v1.22.5_vmware.1-tkg.3