apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-bucket
  labels:
    apps.tanzu.vmware.com/workload-type: web-bucket
    app.kubernetes.io/part-of: hello
    apps.tanzu.vmware.com/has-tests: "true"
  namespace: canary
spec:
  params:
    - name: gitops_repository_name
      value: "trp-gitops-canary"
    - name: endpoint
      value: jellin-tanzu-hello
    - name: bucketName
      value: s3.us-east-2.amazonaws.com
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
