#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-cluster-issuer
spec:
  vault:
    path: #@ "pki_int/sign/" + data.values.vault.role
    server: #@ "http://vault." + data.values.h2o.dns_subdomain + ":8200"
    auth:
      tokenSecretRef:
        name: cert-manager-vault-token
        key: token
