#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-cluster-issuer
spec:
  vault:
    path: #@ "pki_int/sign/" + data.values.vault.role
    server: #@ "http://" + data.values.vault.host + ":8200"
    auth:
      tokenSecretRef:
        name: cert-manager-vault-token
        key: token
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault-token
  namespace: cert-manager
data:
  token: #@ base64.encode(data.values.vault.token)