# Required or else Grype Scanner will have an image pull failure.  Also added a SecretExport to tap-install
apiVersion: v1
kind: Secret
metadata:
  name: scanner-secret-ref
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
