#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap-install-gitops/app"
stringData:
  aws_access_key_id: #@ data.values.r53.access_key
  aws_secret_access_key: #@ data.values.r53.secret_key
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: route53-credentials
  namespace: tap-install
spec:
  toNamespaces:
  - tanzu-system-service-discovery
  - cert-manager
  - kube-system
  - cert-manager
---
