#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-reader-credentials-s3
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap-install-gitops/app"
stringData:
  accesskey: #@ data.values.s3.access_key
  secretkey: #@ data.values.s3.secret_key
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tap-reader-credentials-s3
  namespace: tap-install
spec:
  toNamespaces:
  - '*'
---