apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-ssh
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
spec:
  fromNamespace: tap-install
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-ssl
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
spec:
  fromNamespace: tap-install