#@ load("@ytt:data", "data")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-reader-credentials-s3
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
spec:
  fromNamespace: tap-install
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-ssh
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
    tekton.dev/git-0: github.com
spec:
  fromNamespace: tap-install
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-https
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
    tekton.dev/git-0: https://github.com
spec:
  fromNamespace: tap-install