apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-ssh
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
    tekton.dev/git-0: #@ data.values.git.host
spec:
  fromNamespace: tap-install
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-https
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
    tekton.dev/git-0: #@ data.values.git_pr.host
spec:
  fromNamespace: tap-install