#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: contour-config-app
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: contour-config-app/app
    kapp.k14s.io/change-rule: "upsert after upserting contour"
spec:
  serviceAccountName: tap-install-gitops-sa
  syncPeriod: 1m
  fetch:
  - git:
      url: #@ data.values.git.url
      ref: #@ data.values.git.ref
  template:
  - ytt:
      paths:
      - clusters/common/app-contents/contour-config
  deploy:
  - kapp: {}
