#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tap-config-app
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.2: "upsert after upserting tap"
    kapp.k14s.io/change-group: tap-config-app/app
spec:
  serviceAccountName: tap-install-gitops-sa
  syncPeriod: 1m
  fetch:
  - git:
      url: #@ data.values.git.url
      ref: #@ data.values.git.ref
  template:
  - ytt:
      paths:
      - clusters/appref-1/app-contents/tap
      valuesFrom:
      - secretRef:
          name: tap-install-gitops
  deploy:
  - kapp: {}
