apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-jar
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hello
  namespace: canary
spec:
  params:
    - name: gitops_repository_name
      value: "trp-gitops-canary"
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    image: harbor.h2o-4-1396.h2o.vmware.com/tap/sc/java-jar@sha256:2699e2271c4125c519385cb7d60e612801040d3170d24a7c2ea6fc73a46a0bbc 